### ISSUE TITLE
7월 2주차 오탈자

### ISSUE THREAD

**Issue by eyelove** [TeamSEGO/github-trend-kr#13]
http://teamsego.github.io/github-trend-kr/#/201507-1

오탈자부분 수정부탁드립니다. (__)
원문) 페이지 링크: https://github.com/kilimchoi/engineering-blog
수정) 페이지 링크: https://github.com/kilimchoi/engineering-blogs

**Comment by woongbinni** [comment]
수정하였습니다. 관심 감사드립니다. (--)(__)(--)

송웅빈(woongbinni@gmail.com)

**Comment by ikaruce** [comment]
완료되었으니 이 이슈는 닫을께요.
