### ISSUE TITLE
이제 안하시나요ㅠㅜ

### ISSUE THREAD

**Issue by HoonJin** [TeamSEGO/github-trend-kr#16]
잘 보고 있었는데ㅠ

**Comment by Labyrins** [comment]
좀더 좋은 컨텐츠와 새로운 전략을 준비하기 위해 잠시 쉬는 중입니다. 이런글 보니 어서 다시 진행해야겠다는 생각이 드는군요!

**Comment by HoonJin** [comment]
오, 빠른답변 감사합니다. 기대하겠습니다!^^

**Comment by Labyrins** [comment]
넵. 관심 감사합니다!

**Comment by ikaruce** [comment]
관심가지고 봐주시는 분이 계시니 힘이 나네요. 지금은 정해진 사람들만 참여하는데, 더 많은 분들이 참여하면 어떨까 하는 고민을 가지고 구상 중입니다. 조금만 더 기다려주세요. 절대!! 그만하는건 아니예요. ( 안되면 뭐... 저희끼리 또 하겠죠. :)

**Comment by mavriel** [comment]
오 다행이네요. 업데이트 다시 기다려야 겠네요
